# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Competition.delete_all
Competition.create(:name => "Duke Start-Up Challenge", :location => "Durham, NC", :start_date => "41689", :end_date => "41689", :affiliated_school => "Duke University, Fuqua School of Business", :description => "1. Each team must have at least one currently registered Duke Student, and ideally this student has originated the idea and/or is leading the team.  Teams that do not meet this may be moved to the Alumni/Faculty/Staff part of the competition, where they will still received feedback, etc, but will not be eligible for the student prize pool.                                more rules: http://www.dukestartupchallenge.com/about-us/rules", :winner_id => 0)
Competition.create(:name => "Wharton MBA Buyout Case Competition", :location => "NYC", :start_date => "41691", :end_date => "41691", :affiliated_school => "University of Pennsylvania", :description => "The Wharton MBA Buyout Case Competition is the premier MBA-level LBO case competition in the world. It brings together teams from the leading business schools around the country and world to evaluate and make recommendations for a proposed PE buyout transaction. Presentations will be judged by panel of PE professionals, and extensive networking opportunities are available for participants.", :winner_id => 0)
Competition.create(:name => "Regional Challenge", :location => "Chicago", :start_date => "41698", :end_date => "41698", :affiliated_school => "", :description => "", :winner_id => 0)
Competition.create(:name => "Rotman Design Challenge", :location => "Toronto, Canada", :start_date => "41706", :end_date => "41706", :affiliated_school => "University of Toronto", :description => "At Rotman, we believe that the mindsets and practices behind great design can also be applied to the breakthrough growth of enterprises and institutions. In essence, business design blends design methodologies and business acumen to create a process that helps identify broader opportunities, create new ideas and accelerate market success.", :winner_id => 0)
Competition.create(:name => "Les Foundation Business Plan Challenge", :location => "New York, NY", :start_date => "41722", :end_date => "41723", :affiliated_school => "LES Foundation (no school)", :description => "http://www.lesfoundation.org/competition/PDFs/2014CompetitionGuidelines.pdf", :winner_id => 0)
Competition.create(:name => "Disrupt or Be Disrupted (Columbia Business School’s Odyssey Global MBA Conference and Competition)", :location => "New York", :start_date => "41726", :end_date => "41727", :affiliated_school => "Columbia Business School", :description => "Columbia Business School is hosting the 6th annual Odyssey Global MBA Conference and Competition and this year's theme is Disrupt or Be Disrupted. Teams from the top 20 global MBA programs are invited to participate in a weekend consisting of business competitions, insightful lectures from current business leaders, and fun networking opportunities. It’s a rare opportunity to meet peers from around the world in a global business Olympics.", :winner_id => 0)
Competition.create(:name => "McGinnis Venture Competition", :location => "Pittsburgh, PA", :start_date => "41727", :end_date => "41727", :affiliated_school => "Carnegie Mellon University", :description => "The McGinnis Venture Competition is open to all Carnegie Mellon University undergraduate and graduate students. The competition is for CMU student created, managed, and owned ventures. A CMU student should be CEO, CTO or COO. Members of the student team should also own a significant majority of the equity allocated to all parties. Non-CMU students may be members of the venture’s management team and may participate. However, CMU students should deliver majority to all of the Round 2 video pitch and Final Round live pitch.", :winner_id => 0)
Competition.create(:name => "Business & Society International Aspen Case Competition", :location => "New York, NY", :start_date => "41733", :end_date => "41733", :affiliated_school => "", :description => "Interested in finding the intersection between doing good and doing well? Kellogg is one of 25 leading MBA programs participating in the Aspen Institute’s Business & Society International MBA Case Competition.. To participate, form a team of 3-4 students to tackle a brand new case study requiring innovative thinking at the intersection of corporate profitability and positive social and environmental impact. To enter your team, contact Ali Niederkorn at a-niederkorn@kellogg.northwestern.edu", :winner_id => 0)
Competition.create(:name => "Dartmouth Entrepreneurial Network Business Plan Competition at Tuck", :location => "Hanover, NH", :start_date => "41734", :end_date => "41734", :affiliated_school => "Dartmouth University (Tuck)", :description => "N/A", :winner_id => 0)
Competition.create(:name => "Final Round", :location => "Bentonville, AK", :start_date => "41738", :end_date => "41738", :affiliated_school => "", :description => "", :winner_id => 0)
Competition.create(:name => "Global Social Venture Competition", :location => "Berkely, CA", :start_date => "41738", :end_date => "41740", :affiliated_school => "UC Berkeley - Haas School of Business", :description => "Each entrant team must include a graduate student (current or recent graduate) from any masters-level or post-graduate higher education program in any area of study in the world. The graduate student must be actively involved in the venture (i.e. actively participating in development of the business plan and presentation or actively working on the business).", :winner_id => 0)
Competition.create(:name => "Columbia University Engineering Venture Competition", :location => "New York, NY", :start_date => "41739", :end_date => "41739", :affiliated_school => "Columbia University", :description => "Eligible teams must have at least one principle member currently enrolled in a Columbia University graduate or undergraduate program or must be a young alumnus (five years or less after active enrollment) of any Columbia University school", :winner_id => 0)
Competition.create(:name => "Rice Business Plan Competition", :location => "Houston, TX", :start_date => "41739", :end_date => "41741", :affiliated_school => "Rice University", :description => "Student Enrollment: The competition is for students enrolled in a degree program in the current academic year, i.e., from July 2013 through May 2014. Students in certificate programs are not eligible to participate.  Students from part-time and executive programs are eligible, provided they will receive a degree at the conclusion of their program. Teams from international schools following a different academic calendar should contact RBPC organizers for eligibility considerations. http://alliance.rice.edu/Eligibility/", :winner_id => 2)
Competition.create(:name => "Darden-UVA B-Plan Competition 2.0", :location => "Charlottesville, VA", :start_date => "41746", :end_date => "41746", :affiliated_school => "Darden-University of Virginia", :description => "To enter the Darden-UVA Business Plan Competition, each team must include at least one current UVA student (can be undergraduate, graduate, doctoral, or post-doctoral student), faculty, or staff member. UVA alumni and others are welcome to join teams as well, provided one member of the team is currently affiliated with UVA", :winner_id => 0)
Competition.create(:name => "NAPEC Innovation Challenge (North American Professionals and Entrepreneurs Council)", :location => "New York, NY", :start_date => "41747", :end_date => "41747", :affiliated_school => "Cornell, George Washington, Carnegie Mellon Universities", :description => "The business plan competition is designed to help and reward students who want to pursue an innovative business idea, develop a technology into a marketable product, or have a new approach to a difficult problem or compelling opportunity. The finalists will have the opportunity to showcase their ideas to entrepreneurs, investors and venture capitalists and receive valuable feedback on their ventures.", :winner_id => 0)
Competition.create(:name => "Yale Venture Challenge", :location => "New Haven, CT", :start_date => "41753", :end_date => "41753", :affiliated_school => "Yale University", :description => "The majority of the founders of a team must be students of Yale College or any Yale Graduate School or faculty of any of those institutions. At least one of the principal founders must be a student.", :winner_id => 0)
Competition.create(:name => "NYU Stern $200K Entrepreneurs Challenge", :location => "New York, NY", :start_date => "41754", :end_date => "41754", :affiliated_school => "NYU Stern", :description => "http://www.stern.nyu.edu/experience-stern/about/departments-centers-initiatives/centers-of-research/berkley-center/programs/venture-competitions/rules-eligibility/index.htm", :winner_id => 0)
Competition.create(:name => "Arch Grants Global Business Plan Competition for Entrepreneurs", :location => "St. Louis, MO", :start_date => "41754", :end_date => "41755", :affiliated_school => "None", :description => "Arch Grants is inviting Kellogg entrepreneurs to submit applications for its 3rd annual Global Business Plan Competition. Applications are due by February 21st and finalists will be invited to St. Louis for the competition on April 24-26. Competition winners will receive non-dilutive grants of $50,000 each and must re-locate their startups to St. Louis. Applications must be submitted here and you can read about the launch in Bloomberg BusinessWeek.", :winner_id => 0)
Competition.create(:name => "Harvard New Venture Competition", :location => "Cambridge, MA", :start_date => "41758", :end_date => "41758", :affiliated_school => "Harvard Business School", :description => "http://www.hbs.edu/socialenterprise/mba-experience/new-venture-competition-student/eligibility.html", :winner_id => 0)
Competition.create(:name => "Business Plan Challenge", :location => "Philadelphia, PA", :start_date => "41760", :end_date => "41760", :affiliated_school => "UPenn Wharton", :description => "A team must be led by a degree-candidate student of the University of Pennsylvania (graduate or undergraduate). The team lead/ degree-candidate must have played a significant role in conceiving the venture, hold a key management role in the venture, be actively involved in the business venture, and be a primary presenter for the formal presentations at the Semifinals and Venture Finals and the primary presenter for the elevator pitch at the Venture Finals.  Teams can have members who are not students at the University of Pennsylvannia. http://bpc.wharton.upenn.edu/rules.html", :winner_id => 0)
Competition.create(:name => "2014 Global Venture Labs Investment Competition", :location => "Austin, TX", :start_date => "41760", :end_date => "41762", :affiliated_school => "University of Texas - Austin", :description => "With aspiring entrepreneurs soliciting start-up funds from experienced investors, the VLIC simulates the real-world process of raising venture capital. MBAs from business schools around the globe come to The University of Texas at Austin each May to present their business plans to panels of investors. From among myriad offerings is selected the best new-venture opportunity. With a more than 30-year history, the Competition is the oldest operating inter-business school competition in the world.", :winner_id => 0)
Competition.create(:name => "Stanford's BASES 150k Challenge", :location => "Stanford, CA", :start_date => "41779", :end_date => "41779", :affiliated_school => "Business Association of Stanford Entrepreneurial Students", :description => "All Stanford students, faculty, and alumni are eligible to enter. Though individuals not affiliated with Stanford University are encouraged to participate, any entering team must have at least one of its members affiliated with Stanford University. The size of a team is not restricted, and neither is the number of entries submitted by each person/team.", :winner_id => 2)
Competition.create(:name => "MIT Enterprise Forum of Chicago White Board Challenge", :location => "Chicago", :start_date => "41779", :end_date => "41779", :affiliated_school => "MIT", :description => "The White Board Challenge is MIT Enterprise Forum of Chicago's annual business idea competition. Anyone can submit an application regardless of age, race or school affiliation. The White Board competition allows any individual with a unique business idea to compete for our prize money of a total of $5,000.", :winner_id => 0)
Competition.create(:name => "Booth New Venture Challenge", :location => "Chicago, IL", :start_date => "41788", :end_date => "41788", :affiliated_school => "University of Chicago Booth School of Business", :description => "Each team is required to have at least one current University of Chicago student in order to participate.", :winner_id => 0)
Competition.create(:name => "MBA World Trophy", :location => "Dublin, Ireland", :start_date => "41886", :end_date => "41888", :affiliated_school => "", :description => "The MBA World Trophy is a unique business gathering in one of Europe’s most dynamic and innovative cities. Held over three days in Dublin with the full support of the Irish government, Teams will pitch their business models to an exclusive panel of VCs, participate in workshops in Innovation, Finance, Growth and Leadership and attend several networking events. Each team will be paired with a mentor and on the final day each team will present their final pitch to our judging panel to compete for a top prize of $10,000 and the MBA World Trophy. We are looking for early stage college startups using lean startup methodologies. We have partnered with some world class universities again this year including: NYU Stern USA, Boston College USA, EI Spain, UCD Ireland, Ipade Mexico, Universidad Pacífic Peru, IMD Switzerland, London Business School UK, Warwick UK , Wharton USA, Thunderbird Arizona USA, Fordham New York USA, Rotman Toronto Canada and DCU Ireland", :winner_id => 0)
Competition.create(:name => "Brands+Startups™ 2014 Mobile Marketing Accelerator & Competition", :location => "Chicago, IL", :start_date => "41900", :end_date => "41900", :affiliated_school => "None", :description => "The winners will be awarded projects with our vested brands. Brand coaches will fight each other for the startups they want on their team, then mentor them through elimination rounds throughout the summer.", :winner_id => 0)

Startup.delete_all
Startup.create(:name => "Addison Carlyle Diamonds", :founding => 2014, :description => "The go-to marketplace for high value, affordable diamond engagement rings", :competition_id => 0 )
Startup.create(:name => "Innoblative", :founding => 2013, :description => "Innovating the treatment of breast cancer", :competition_id => 0)

Winner.delete_all
Winner.create(:startup_id => 2, :place => 3)
Winner.create(:startup_id => 2, :place => 1)

Kellogg_founder.delete_all
Kellogg_founder.create(:name => "Tyler Wanke", :grad_year => 2015, :program => "MDMBA", :startup_id => 2)
Kellogg_founder.create(:name => "Jason Sandler", :grad_year => 2015, :program => "JDMBA", :startup_id => 2)
Kellogg_founder.create(:name => "Sara Katherine Clay", :grad_year => 2015, :program => "2YMBA", :startup_id => 1)
Kellogg_founder.create(:name => "Katherine Augustus", :grad_year => 2015, :program => "2YMBA", :startup_id => 1)
